pipeline {
    agent any

    environment {
        TARGET_IP = "35.154.85.149"
    }

    stages {

        stage('Prepare Script') {
            steps {
                writeFile file: 'ip_monitor.sh', text: '''
#!/bin/bash

IP=$1
echo "Checking IP: $IP"
ping -c 3 $IP
'''
            }
        }

        stage('Run Monitoring') {
            steps {
                bat '"C:\\Program Files\\Git\\bin\\bash.exe" ip_monitor.sh %TARGET_IP%'
            }
        }
    }
}
