pipeline {
    agent any

    environment {
        TARGET_IP = "35.154.85.149"
    }

    stages {

        stage('Prepare Script') {
            steps {
                writeFile file: 'ip_monitor.sh', text: '''
#!/bin/bash

IP=$1
echo IP is $IP
'''

                // Windows command
                bat 'echo Script created'
            }
        }

        stage('Run Script') {
            steps {
                bat 'echo Running on Windows'
            }
        }
    }
}
